name: classinterim
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get_storage:
  image_picker: ^0.6.7+11
  firebase_core: "0.5.0"
  firebase_storage: ^4.0.1
  cloud_firestore: ^0.14.0+2
  firebase_messaging: ^6.0.16
  flutter_spinkit: ^4.1.2+1
  cached_network_image: ^2.0.0
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  intl: ^0.16.1
  keyboard_visibility: ^0.5.6
  local_auth: ^0.6.1
  bottom_navy_bar: ^5.6.0
  shared_preferences: ^0.5.12+4
  http:



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/Logo.png
    - assets/noimage.png
